(set! *warn-on-reflection* true)
(set! *unchecked-math* :warn-on-boxed)
;;----------------------------------------------------------------
(ns palisades.lakes.elements.scripts.topos.topics
  
  {:doc "Topics in category and topos theory, dependencies."
   :author "palisades dot lakes at gmail dot com"
   :version "2020-09-07"}
  
  (:require [clojure.string :as s]
            [clojure.java.io :as io]
            [clojure.pprint :as pp]))
;; clj src\scripts\clojure\palisades\lakes\elements\scripts\topos\topics.clj
;;----------------------------------------------------------------
;; topic and list of rank in various cat theory intros:

(def topics 
  {:Adámek_et_al 
   [:category
    :functor
    :duality
    :monepisic
    :categories_of_categories
    :small_category
    :quasicategory
    :subcategory
    :concrete_category
    :functor
    :natural_transformation
    :injective_object
    :source_sink
    :co_limit
    :co_completeness
    :pullback_pushout
    :adjoint_functor
    :monad
    :cartesian_closed_category]
   :Asperti_and_Longo 
   [:category
    :diagram
    :monepisic
    :subobject
    :initial_terminal_object
    :co_product
    :exponential
    :equalizer
    :pullback
    :partial_morphism
    :complete_object
    :subobject_classifier
    :topos
    :functor
    :natural_transformation
    :cartesian_closed_category
    :yoneda
    :presheaf
    :monoidal_closed_category
    :monad
    :linear_logic
    :universal_arrow
    :adjunction
    :monad
    :co_limit
    :indexed_category]
   :Awodey 
   [:category
    :isomorphism
    :free_category
    :monepisic
    :initial_terminal_object
    :generalized_element
    :co_product
    :hom_set
    :finitely_presented_category
    :subobject
    :pullback
    :co_limit
    :exponential
    :cartesian_closed_category
    :natural_transformation
    :monoidal_category
    :equivalence
    :yoneda
    :topos
    :adjoint
    :monad]
   :Barr_Wells 
   [:category
    :monepisic
    :diagram
    :natural_transformation
    :yoneda
    :linear_sketch
    :2_category
    :product_sum
    :cartesian_closed_category
    :co_limit
    :equalizer
    :pullback
    :co_cone
    :fibration
    :wreath_product
    :adjoint
    :scott_domain
    :topos
    :presheaf
    :monoidal_category]
   :Geroch 
   [:category
    :monepisic
    :commuting_diagram
    :co_product
    :functor
    :free_construction
    :homology_functor]
   :Goldblatt 
   [:category
    :composition
    :monepisic
    :initial_terminal_object
    :duality
    :co_product
    :co_equalizer
    :co_limit
    :pullback_pushout
    :completeness
    :exponential
    :subobject
    :classifier
    :topos
    :bundle
    :sheaf
    :monoid_action
    :power_object]
   :Hillman 
   [:category
    :diagram
    :commute
    :subcategory
    :skeleton
    :monepisic
    :duality
    :subobject
    :initial_terminal_object
    :element
    :co_product
    :universal_property
    :co_equalizer
    :pullback_pushout
    :co_cone
    :co_limit
    :functor
    :natural_transformation
    :slice_category
    :yoneda
    :adjoint
    :exponential
    :topos]
   :Lawvere_and_Schanuel 
   [:category
    :functor
    :subcategory
    :monepisic
    :idempotent
    :universal_property
    :initial_terminal_object
    :co_product
    :points_of_an_object
    :distributive_and_linear_category
    :universal_construction
    :arrow_object
    :exponential
    :contravariant_parts_functor
    :subobject
    :topos
    :co_discrete_object
    :monoid]
   :Leinster 
   [:category
    :duality
    :contra_co_variant_functor
    :presheaf
    :faithful_functor
    :subcategory
    :natural_transformation
    :isomorphism
    :equivalence
    :adjoint
    :initial_terminal_object
    :co_unit
    :representable
    :co_limit
    :co_product
    :pullback_pushout
    :equalizer
    :diagram
    :co_cone
    :monepisic
    :cartesian_closed_category]
   :MacLane
   [:category
    :functor
    :natural_transformation
    :monepisic
    :zero
    :hom_set
    :duality
    :contravariance
    :comma_category
    :free_category
    :universal_arrow
    :yoneda
    :co_product
    :co_limit
    :representable_functor
    :adjoint
    :adjoint_functor
    :cartesian_closed_category
    :monad
    :split_co_equalizer
    :monoidal_category
    :action
    :loop_and_suspension
    :co_kernel
    :additive_category
    :abelian_category
    :co_end
    :kan_extension
    :nerve
    :bicategory]
   :Perrone 
   [:category
    :monepisic
    :functor
    :natural_transformation
    :universal_property
    :yoneda
    :co_limit
    :adjunction
    :co_unit
    :universal_arrow
    :adjoint_functor
    :co_monad]
   :Riehl 
   [:category
    :functor
    :natural_transformation
    :universal_property
    :representable
    :yoneda
    :co_limit
    :adjunction
    :monad
    :kan_extension]
   :DSpivak 
   [:category
    :diagram
    :olog
    :co_product
    :co_limit
    :category
    :functor
    :natural_transformation
    :adjoint_functor
    :monad
    :operad]
   :vanOosten 
   [:category
    :functor
    :monepisic
    :initial_terminal_object
    :natural_transformation
    :yoneda
    :category_equivalence
    :co_cone
    :co_limit
    :equalizer
    :pullback_pushout
    :co_product
    :regular_category
    :subobject
    :adjunction
    :adjoint_functor
    :co_completeness
    :monad
    :cartesian_closed_category]})
;;----------------------------------------------------------------
(defn summary []
  (println "authors: " (count topics))
  (let [onion 
        (sort (reduce into #{} (vals topics)))]
    (println "topics: " (count onion))
    (pp/pprint onion)))
;;----------------------------------------------------------------
(summary)
;;----------------------------------------------------------------
